### ISSUE TITLE
Clones?

### ISSUE THREAD

**Issue by msdsoftware** [rototor/pdfbox-graphics2d#13]
I am implementing pdfbox in a couple Java apps and am using pdfbox-graphics2d as middle layer since all my plot drawing code is Graphics2D oriented.

Things went very well with one app, but with the other I am getting a "Not all PdfGraphics2D clones where destroyed" exception thrown when I call PdfBoxGraphics2D.dispose().

Can you provide some guidance on what this means? Is it that I have created a Graphics2D object somewhere and forgotten to dispose of it, or is it something else?

(Minor nit: The msg should say "were" rather than "where".)

**Comment by msdsoftware** [comment]
Kept poking at it, and indeed the problem was that I had created a graphics object and not disposed of it.

Nevertheless, please fix the typo in the exception.

And maybe some extra commenting in the code to indicate that the exception could be caused by this?

**Comment by rototor** [comment]
@msdsoftware Please look at the commit: Are the comments more clear now?

**Comment by msdsoftware** [comment]
@rototor, Perfect.
