### ISSUE TITLE
[question] SVG and fonts

### ISSUE THREAD

**Issue by jonathannaguin** [rototor/pdfbox-graphics2d#15]
Hello,

We are drawing SVGs in a PDF and we have noticed the following:

- Given a SVG that uses a font-family like "Aladin".
- If the font is installed on the machine where the PDFBox/graphics2d runs then the PDF will preserve the font on the text. If I then delete the font and open the PDF, the PDF will still show the text using "Aladin".
- If the font is not installed on the machine when I generate the PDF, then it will never show the text with the chosen font, not even if I install the font later on in the machine.

I don't know how the library is rendering the SVG internally, so I am not sure if this is the expected behaviour when using fonts in SVG. Is the SVG rendered at the moment the PDF gets created? or is the SVG rendered when the user opens the PDF on a viewer?

Thanks!

**Comment by rototor** [comment]
The text is rendered with the font the moment the SVG is painted into the PDF. Depending on what font strategy you choose the font is subset and embedded into the PDF (the default) or drawn using vector shapes. For details look [here](https://github.com/rototor/pdfbox-graphics2d#rendering-text-using-fonts-vs-vectors).

So, yes you need the font while creating the PDF. This is a somewhat hard requirement, as the font is needed to get all the text geometric information.

PDFs don't understand SVGs, so the SVG must be translated into the corresponding PDF commands/resources. How are you using this library? Directly using this library in combination with Batik or indirect using [OpenHTMLtoPDF](https://github.com/danfickle/openhtmltopdf)? This library does not render SVG itself, it just provides a Graphics2D adapter to allow in combination with Batik to render a SVG into a PDF.

**Comment by jonathannaguin** [comment]
Thanks for your quick reply!
Yes, I am using it directly in combination with Batik, I had hoped the SVG would simply refer to a font that may or not may be installed on the target machine, but it seems that is not the case.

Thanks again!

**Comment by rototor** [comment]
If you want to save space in the PDF you can use PdfBoxGraphics2DFontTextDrawerDefaultFonts - this replaces the fonts with the default builtin PDF fonts.
