### ISSUE TITLE
PdfBoxGraphics2DFontTextDrawer.iterateRun - off-by-one leads to wrong font style

### ISSUE THREAD

**Issue by kiwiwings** [rototor/pdfbox-graphics2d#27]
The TextDrawer has a off-by-one which leads to shifted font styles in [text mode](https://github.com/rototor/pdfbox-graphics2d/files/5507036/alterman_security-ppt-text.pdf) - in [shape mode](https://github.com/rototor/pdfbox-graphics2d/files/5507035/alterman_security-ppt-shapes.pdf) it works correctly.

Please apply [the patch](https://github.com/rototor/pdfbox-graphics2d/files/5507038/drawer-patch.diff.zip)

If you provide a new release by December '20, I'm happy to include it in Apache POI, as we use your library now to render powerpoint slides to PDF ... otherwise I just use the copied class - Thank you for your great implementation!

**Comment by kiwiwings** [comment]
Sorry ... there seems to be another error. it switches now to shape mode and I've missed that before ... I'll provide another patch when fixed.

**Comment by kiwiwings** [comment]
ok [this patch](https://github.com/rototor/pdfbox-graphics2d/files/5507137/drawer-patch.diff.zip) looks better

**Comment by rototor** [comment]
I've just released version 0.28 with your fix. Thanks for pointing out this problem.
