### ISSUE TITLE
IllegalArgumentException thrown in DrawString method

### ISSUE THREAD

**Issue by Kischloren** [rototor/pdfbox-graphics2d#31]
Would it be possible to check <code>str</code> value in <code>drawString(String str, float x, float y)</code> method which will prevent the following IllegalArgumentException?

<code>java.lang.IllegalArgumentException: Can`t add attribute to 0-length text at java.base/java.text.AttributedString.addAttribute(AttributedString.java:322)</code>

Thank you very much.

https://github.com/rototor/pdfbox-graphics2d/blob/7a9a7c0ba2f88373dbb6376f8809d416f6eb461a/graphics2d/src/main/java/de/rototor/pdfbox/graphics2d/PdfBoxGraphics2D.java#L538

**Comment by rototor** [comment]
I'll do a release with this fix later today.

**Comment by rototor** [comment]
I've just released version 0.33 with the fix.
