### ISSUE TITLE
Adding test scope to outer dependencies in the pom of extended-tests

### ISSUE THREAD

**Issue by pgrt** [rototor/pdfbox-graphics2d#34]
Hi,

Because the outer dependencies of extended-tests are only used in the tests, I believe they can be safely marked with
    <scope>test</scope>
like in the attached patch.

[missing_test_scope.txt](https://github.com/rototor/pdfbox-graphics2d/files/7965969/missing_test_scope.txt)

Best,
Pierre

**Comment by rototor** [comment]
Thanks for the report, I've applied your patch. Regarding the extended-tests package I post some comments on #33.
