### ISSUE TITLE
PdfBoxGraphics2DFontTextDrawer.getFontMetrics always floors the width

### ISSUE THREAD

**Issue by Lorgod** [rototor/pdfbox-graphics2d#35]
I ran into an issue with the FontMetrics provided by the PdfBoxGraphics2DFontTextDrawer when using it for the method SwingUtilities.layoutCompoundLabel. The method tries to shorten the given text if necessary and add three dots at the end (...) to indicate that the original string was longer. To do this the method goes character by character until the available width is reached. 
The issue now is that the FontMetrics always floors the width so that the sum of the width of the individual characters will always be (significantly) lower than the actual width of the string represented by these characters (for non monospaced fonts).
I think this should be rounded (like sun.font.FontDesignMetrics) by adding 0.5f before casting to an int.

**Comment by rototor** [comment]
I made a simple test case for this. As documented on the stringWidth() method, this is always off. I.e. the sum of all single char widths will never be the width of the complete string.

This is how it looks like without the rounding like FontDesignMetrics:
<img width="1138" alt="image" src="https://user-images.githubusercontent.com/711674/163026617-21a3f6d8-679f-44e3-a695-8e5c97aebf4e.png">

And this is how it looks like with the rounding:
<img width="1017" alt="image" src="https://user-images.githubusercontent.com/711674/163026671-1d312e0e-4cb3-4968-b657-9c4901af8bd0.png">

You can see that the first case underestimates the string width, the second ("fixed") version overestimates the stringWidth.

So relying on this is broken in any way. But with this "fix" it is now broken the same way as in the JDK. So its now more consistent.

**Comment by rototor** [comment]
I just release version 0.37 with this fix.

**Comment by Lorgod** [comment]
Thank you for your quick response and the new release. Much appreciated.
