### ISSUE TITLE
mapColor parameters in RGBtoCMYKColorMapper

### ISSUE THREAD

**Issue by iocoker** [rototor/pdfbox-graphics2d#41]
Hi, so I was using the tests to generate sample PDF files, and in RenderSVGsTest.java, the method `renderSVGCMYK` doesn't render the Shapes in CMYK. They were still RGB.

So I went through the code and observed in `de/rototor/pdfbox/graphics2d/RGBtoCMYKColorMapper.java`, line: https://github.com/rototor/pdfbox-graphics2d/blob/2d9af186b85f0c3520611174cb4ba81391604d3b/graphics2d/src/main/java/de/rototor/pdfbox/graphics2d/RGBtoCMYKColorMapper.java#L43

Which extends and overrides this:
https://github.com/rototor/pdfbox-graphics2d/blob/2d9af186b85f0c3520611174cb4ba81391604d3b/graphics2d/src/main/java/de/rototor/pdfbox/graphics2d/PdfBoxGraphics2DColorMapper.java#L26

Which is an implementation of this interface:
https://github.com/rototor/pdfbox-graphics2d/blob/2d9af186b85f0c3520611174cb4ba81391604d3b/graphics2d/src/main/java/de/rototor/pdfbox/graphics2d/IPdfBoxGraphics2DColorMapper.java#L38

Has different sets of parameters and I can't find any overload which requires a `(PDPageContentStream, Color)`.

I might be wrong though.
Great work btw 🙌

**Comment by rototor** [comment]
Ups, that was a leftover from some refactoring. You can get the PDPageContentStream using env.getContentStream().
