### ISSUE TITLE
What is a good way to handle "Page N of M" drawing?

### ISSUE THREAD

**Issue by AlexGeller1** [rototor/pdfbox-graphics2d#42]
Hi,
we have the problem that we create larger documents with multiple pages on which text or barcodes for enveloping machines are drawn that contain information about the total number of pages (e.g. a string "this is page 4 of 85"). Computing the total number of pages before rendering the first page is of course possible but that would be too costly for large documents.
I don't want to propose a solution (not expert enough) but instead perhaps share a small sample that illustrates the problem and shows one possible solution.

I added this method to PdfBoxGraphics2D:
```java
    /** 
    * Creates a context for which dispose() can be called after this.dispose() has been called without violating the order of calls.
    *
    * @return a copy of this Graphics.
    */
    public PdfBoxGraphics2D createAsyncContext()
    {
        try
        {
            PdfBoxGraphics2D g = new PdfBoxGraphics2D(document, bbox, this);
            contentStream.drawForm(g.xFormObject);
            return g;
        }
        catch (IOException e)
        {
            throwException(e);
            return null;
        }
    }
```
The method draws a reference to an XObject for which it returns a graphics context. The drawing to the XObject happens later when the page count is known. (edit: removed incorrect sentence about sharing drawings here).

Then I create a pdf with this test program as follows:
```java
import java.util.List;
import java.util.ArrayList;
import java.io.IOException;

import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDPage;
import org.apache.pdfbox.pdmodel.PDPageContentStream;
import org.apache.pdfbox.pdmodel.common.PDRectangle;
import org.apache.pdfbox.pdmodel.graphics.form.PDFormXObject;

import de.rototor.pdfbox.graphics2d.PdfBoxGraphics2D;

public class PageNOfMExample
{
    public static void main(String[] args) throws IOException
    {
        PDDocument document = new PDDocument();

        List<PdfBoxGraphics2D> pageNumberGs = createPages(document);  //render all pages

        int totalNumberOfPages = document.getNumberOfPages(); //now we know the total number of pages and can draw the strings
        for (int i = 0; i < pageNumberGs.size(); i++)
        {
            PdfBoxGraphics2D pageNumberG = pageNumberGs.get(i);
            pageNumberG.setColor(java.awt.Color.BLACK);
            pageNumberG.drawString("This is page " + (i + 1) + " of " + totalNumberOfPages, 100, 120);
            pageNumberG.dispose();
        }
        document.save("PageNofM.pdf");
        document.close();
    }
    static List<PdfBoxGraphics2D> createPages(PDDocument document) throws IOException
    {
        List<PdfBoxGraphics2D> pageNumberGs = new ArrayList<>();
        for (int i = 0; i < 100; i++)
        {
            PDPage page = new PDPage(PDRectangle.A4);
            document.addPage(page);

            PdfBoxGraphics2D pageG = new PdfBoxGraphics2D(document, PDRectangle.A4.getWidth(), PDRectangle.A4.getHeight());
            pageG.setColor(java.awt.Color.BLACK);
            pageG.drawString("Some text", 100, 100);

            PdfBoxGraphics2D pageNumberG = pageG.createAsyncContext(); //new method to create a context for which dispose() can be called after dispose() to the creating context has been called.
            pageNumberGs.add(pageNumberG);

            pageG.drawString("Some more text", 100, 140);

            pageG.dispose();

            PDPageContentStream contentStream = new PDPageContentStream(document, page);
            contentStream.drawForm(pageG.getXFormObject());
            contentStream.close();
        }
        return pageNumberGs;
    }
}
```
Thanks in advance for any suggestions

**Comment by rototor** [comment]
For things like page numbers etc. I would really suggest using [OpenHTMLToPDF](https://github.com/danfickle/openhtmltopdf), as this does all that and also does all the layout stuff. It really saves a lot of work...

I don't like the createAsyncContext() method, as this has no defined / enforced life cycle. If you don't dispose the gfx you get some PDFBox reading while writer is open exceptions when calling document.save(). You also get the GFX state at the time you call your createAsyncContext(). This is all a bit "random".

You can append/prepend to a page later if you know the page count etc. See this adapted example [PageNofMExample](https://github.com/rototor/pdfbox-graphics2d/blob/master/graphics2d/src/test/java/de/rototor/pdfbox/graphics2d/PageNofMExample.java).

This should do everything you need.

**Comment by AlexGeller1** [comment]
Thanks a ton, it works like a charm! 
Thanks also for the suggestion of using OpenHTMLToPDF (sounds like a very useful project)! 
In this particular case however, I am dealing with post-layout drawings in the sense that the computation of page breaks, item positions and sizes is already done by the software and the source page description language is not HTML.
