### ISSUE TITLE
drawIssue with incorrect argument

### ISSUE THREAD

**Issue by fransbouwmans** [rototor/pdfbox-graphics2d#45]
Line 655 of PdfBoxGraphics2D.java 

public boolean drawImage(Image img, int dx1, int dy1, int dx2, int dy2, int sx1, int sy1,
            int sx2, int sy2, ImageObserver observer)
    {
        return drawImage(img, dx1, dy1, dx2, dy2, sx1, **sy2**, sx2, sy2, null, observer);
    }

sy2 is used instead of sy1, as a result the scaling always is 0 and the image is no longer visible.

**Comment by rototor** [comment]
Ups, you are right... I've just released version 0.41 with a fix for this.
