### ISSUE TITLE
System.err in PdfBoxGraphics2DFontTextDrawer 

### ISSUE THREAD

**Issue by pmds-martins** [rototor/pdfbox-graphics2d#49]
Hello, my name is Pedro Martins and I'm here to report what I think is a bug.

I noticed that in the PdfBoxGraphics2DFontTextDrawer class of the de.rototor.pdfbox.graphics2d package, an error is being printed using System.err instead of creating an error entry through a logger.

Here is the line of code: https://github.com/rototor/pdfbox-graphics2d/blob/cbc3c4551832dc7b844c8e73288ea6eb554d3aa3/graphics2d/src/main/java/de/rototor/pdfbox/graphics2d/PdfBoxGraphics2DFontTextDrawer.java#L415

**Comment by rototor** [comment]
Well this tells the developer why he won't see a text at all. Using SL4J would be nicer here, but I won't pull in this dependency without any pressing need. I see no reason to suppress this error.

**Comment by pmds-martins** [comment]
Hello rototor,

You don't need to use SL4J, you can use a Logger from java logging framework.
Actually it's very important for me to have a logger when this exception is thrown.

Best regards

**Comment by rototor** [comment]
I wont have time for that in the near future. But feel free to provide a PullRequest.

**Comment by rototor** [comment]
I assume you need a new released version soon?

**Comment by pmds-martins** [comment]
Yes :)

**Comment by rototor** [comment]
I've just released version 0.43. Should show up very soon on maven central.
