### ISSUE TITLE
add pdfbox 3.0.0 support

### ISSUE THREAD

**Issue by pjfanning** [rototor/pdfbox-graphics2d#55]
I had a quick look but it seems non-trivial - https://github.com/rototor/pdfbox-graphics2d/pull/54

https://pdfbox.apache.org/3.0/migration.html

**Comment by rototor** [comment]
sorry, did not yet have time for a 3.0 release. There is already a branch for this.

**Comment by rototor** [comment]
I've just release pdfbox-graphics2d-3.0.0 - it should already be on maven central. The pdfbox-3.0.0 branch already contains all needed changes.

**Comment by pjfanning** [comment]
Thanks @rototor - we use your lib in Apache POI. I'll try upgrading POI to use your new release.
