### ISSUE TITLE
SVG texts not searchable in PDF

### ISSUE THREAD

**Issue by YSArch** [rototor/pdfbox-graphics2d#9]
How to add SVG as vector image rather than raster in PDF? Thanks

**Comment by rototor** [comment]
You need to let Batik draw using this library. You can look up how to do that [here](https://github.com/rototor/pdfbox-graphics2d/blob/master/src/test/java/de/rototor/pdfbox/graphics2d/RenderSVGsTest.java).

If you are creating a bigger report with many graphics and texts you should consider using [OpenHtmlToPdf](https://github.com/danfickle/openhtmltopdf). With OpenHtmlToPdf  you can create PDF reports using HTML and also include SVG graphics. It is using this library under the hood for the SVG graphics.
